### ISSUE TITLE
More = white screen

### ISSUE THREAD

**Issue by JonnyTech** [316k/android-tap-the-black-tiles#1]
In the "More..." section, selecting either "About this game" or "High scores" results in a blank white screen. Android Lollipop - CyanogenMod 5.1.1

PS: Great game!

**Comment by 316k** [comment]
Thanks for the interest ! :)

If I sent you a corrected apk, would you be able to try it and tell me if it's corrected ? I'm still running Kit Kat, and my poor computer has trouble running an Android emulator...

By the way, may I ask how you found that project ? I submitted it on f-droid, but it looks like it hasn't been added yet.

**Comment by 316k** [comment]
New APK here -> https://github.com/316k/android-tap-the-black-tiles/releases/tag/v1.0.2

**Comment by JonnyTech** [comment]
Thanks for the quick reply - I'll test it shortly.

I did find it on F-Droid - yesterdays repo scan picked it up in the what's new section.

It hasn't made the fdroig.org homepage yet but it is there: https://f-droid.org/repository/browse/?fdid=org.legtux.m_316k.taptheblacktiles

The in-game scrolling can be a bit jittery, is that because it is using webview?

**Comment by JonnyTech** [comment]
OK, the new version works - well done!

I had to uninstall the fdroid version first because it was probably compiled with a different signature. That meant that all my high scores were wiped out, which made me find another bug: Before any scores are generated, going to the high scores page displays a blank black screen which looks like the program has stopped. Playing a game then going back shows the high score table correctly. Also, clearing high scores from the paranoid button(s) also leads to an empty page. It really needs some kind of text there.

BTW, idea for a new level: reverse scrolling, ie tiles move away from player instead of towards them.

**Comment by 316k** [comment]
Thanks for helping out, I'll correct that :)

I have splitted your idea and bug into two new issues.

The game is indeed all rendered in a webview, and playing with the DOM is a bit resource-hungry. The reverse scrolling mode existed in a previous version, but it was really hackish and it gave completely random results depending on the browser... I'll find a better way to do it and I'll re-enable it !
