### ISSUE TITLE
F-Droid question

### ISSUE THREAD

**Issue by valerio-bozzolan** [316k/android-tap-the-black-tiles#10]
Hello! Nice game! I've discovered it from F-Droid :D

I'm contacting you because unfortunately it seems that F-Droid needs to re-build this app in order to fix a [build security issue](https://f-droid.org/wiki/page/AntiFeature:DisabledAlgorithm) (nothing related to your source code).

Fortunately, in order to fix it, you can simply release a "new dummy" app version. For example you can simply increment your `versionCode` and `versionName` in the [build.grandle](/316k/android-tap-the-black-tiles/blob/master/app/build.gradle) and pushing the result with a new git tag.

Can you kindly do that? :D

Thanks and sorry for this inconvenient.

**Comment by 316k** [comment]
Something like that last commit ?

**Comment by valerio-bozzolan** [comment]
You were very quick :)

I think we can close this. Thank you very much!

**Comment by 316k** [comment]
No problem, thanks for the interest !
