### ISSUE TITLE
Project link

### ISSUE THREAD

**Issue by JonnyTech** [316k/android-tap-the-black-tiles#4]
The link on the about page points to https://github.com/316k/tap-the-black-tiles rather than https://github.com/316k/android-tap-the-black-tiles

**Comment by 316k** [comment]
Actually, if you look at the source code, the Android project is nothing but a WebView manager :

https://github.com/316k/android-tap-the-black-tiles/blob/master/app/src/main/java/org/legtux/m_316k/taptheblacktiles/WebActivity.java

The game has it's own repo, which is the one linked in the about page : https://github.com/316k/android-tap-the-black-tiles/tree/master/app/src/main/assets

So the link in the about page points to the "real" project. I could add the link for the android port in the about page, though.
