### ISSUE TITLE
Option to disable vibration

### ISSUE THREAD

**Issue by tbeitter** [316k/android-tap-the-black-tiles#5]
Please give an option to disable the vibration. It is a battery killer and after some games really annoying :)

Thanks for the game!

Best,
Til

**Comment by TheLastProject** [comment]
I couldn't +1 this enough. Every time I hit a tile my phone vibrates and it feels like I'm being punished for hitting the tiles. I can understand some people may like it, but for me, it's just annoying (also the reason I don't play the Flappy Droid Android 5 easter egg, which does the same) :(

**Comment by 316k** [comment]
I considered that at some point, but when I found out that disabling the vibration at my phone's level did the same, I lost interest in making this option available... Since that's a cheap workaround and the option is quite simple to add, I'll add it soon ;)

**Comment by 316k** [comment]
Done !
New release here : https://github.com/316k/android-tap-the-black-tiles/releases/tag/v1.1
It should also be updated on F-Droid eventually.
