### ISSUE TITLE
Wrong minSdkVersion: increase or do conditional method calls

### ISSUE THREAD

**Issue by dllud** [316k/android-tap-the-black-tiles#7]
On [app/build.gradle:9](https://github.com/316k/android-tap-the-black-tiles/blob/master/app/build.gradle#L9) minSdkVersion is set to 14. However the app is using at least one method that was only added on API level 19: [android.webkit.WebView.setWebContentsDebuggingEnabled](https://developer.android.com/reference/android/webkit/WebView.html#setWebContentsDebuggingEnabled%28boolean%29). It is called on [WebActivity.java:35](https://github.com/316k/android-tap-the-black-tiles/blob/master/app/src/main/java/org/legtux/m_316k/taptheblacktiles/WebActivity.java#L35).

When I open the game on Android 4.2 (API level 17) I instantly get the following FC:

```
I/ActivityManager(14686): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.legtux.m_316k.taptheblacktiles/.WebActivity} from pid 14947
I/ActivityManager(14686): Start proc org.legtux.m_316k.taptheblacktiles for activity org.legtux.m_316k.taptheblacktiles/.WebActivity: pid=21922 uid=10103 gids={50103, 1028}
W/Trace   (21922): error opening trace file: No such file or directory (2)
I/dalvikvm(21922): Could not find method android.webkit.WebView.setWebContentsDebuggingEnabled, referenced from method org.legtux.m_316k.taptheblacktiles.WebActivity.onCreate
W/dalvikvm(21922): VFY: unable to resolve static method 11643: Landroid/webkit/WebView;.setWebContentsDebuggingEnabled (Z)V
D/dalvikvm(21922): VFY: replacing opcode 0x71 at 0x0016
D/AndroidRuntime(21922): Shutting down VM
W/dalvikvm(21922): threadid=1: thread exiting with uncaught exception (group=0x41be3930)
```

Please increase minSdkVersion, or better, if this method call is accessory place it in a if like this:

``` Java
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    WebView.setWebContentsDebuggingEnabled(true);
}
```

You might want check your code for other methods which aren't available on API 14.

**Comment by 316k** [comment]
Whoo, that's bad. Thanks a lot for noticing that...
I corrected it here : 21132f450b7e660a43ff6f6af8b1f6da61259a99
